# Generated by Django 5.1.6 on 2025-05-28 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("corporate", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="companies",
            options={"verbose_name": "Компания", "verbose_name_plural": "Компании"},
        ),
    ]
