# Generated by Django 5.1.6 on 2025-05-29 05:45

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corporate", "0002_alter_companies_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemCollections",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=250,
                        unique=True,
                        verbose_name="Наименование коллекции",
                    ),
                ),
            ],
            options={
                "verbose_name": "Коллекция",
                "verbose_name_plural": "Коллекции",
            },
        ),
        migrations.CreateModel(
            name="ItemColors",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=250, unique=True, verbose_name="Наименование цвета"
                    ),
                ),
            ],
            options={
                "verbose_name": "Цвет",
                "verbose_name_plural": "Цвета",
            },
        ),
        migrations.CreateModel(
            name="ItemProperty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=250,
                        unique=True,
                        verbose_name="Наименование характеристики",
                    ),
                ),
            ],
            options={
                "verbose_name": "Характеристика",
                "verbose_name_plural": "Характеристики",
            },
        ),
        migrations.CreateModel(
            name="ItemSizes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=250, unique=True, verbose_name="Наименование размера"
                    ),
                ),
            ],
            options={
                "verbose_name": "Размер",
                "verbose_name_plural": "Размеры",
            },
        ),
        migrations.CreateModel(
            name="CatTree",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="Наименование категории"
                    ),
                ),
                ("lft", models.PositiveIntegerField(editable=False)),
                ("rght", models.PositiveIntegerField(editable=False)),
                ("tree_id", models.PositiveIntegerField(db_index=True, editable=False)),
                ("level", models.PositiveIntegerField(editable=False)),
                (
                    "parent",
                    mptt.fields.TreeForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="corporate.cattree",
                        verbose_name="Родительская категория",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Items",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "guid",
                    models.CharField(max_length=200, null=True, verbose_name="1c id"),
                ),
                (
                    "fullname",
                    models.CharField(max_length=250, verbose_name="Наименование 1С"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Наименование")),
                (
                    "article",
                    models.CharField(
                        default="б/а", max_length=250, verbose_name="Артикль"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Краткое описание товара",
                        null=True,
                        verbose_name="Описание",
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Вес",
                    ),
                ),
                (
                    "volume",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Объем",
                    ),
                ),
                (
                    "pict",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="itempic/",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "cat",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="corporate.cattree",
                        verbose_name="Категория",
                    ),
                ),
                (
                    "collection",
                    models.ManyToManyField(
                        to="corporate.itemcollections", verbose_name="Коллекции"
                    ),
                ),
                (
                    "colors",
                    models.ManyToManyField(
                        to="corporate.itemcolors", verbose_name="Доступные цвета"
                    ),
                ),
                (
                    "item_property",
                    models.ManyToManyField(
                        to="corporate.itemproperty", verbose_name="Характеристики"
                    ),
                ),
                (
                    "sizes",
                    models.ManyToManyField(
                        to="corporate.itemsizes", verbose_name="Доступные размеры"
                    ),
                ),
            ],
            options={
                "verbose_name": "Номенклатура",
                "verbose_name_plural": "Номенклатуры",
            },
        ),
    ]
