# Generated by Django 5.1.6 on 2025-05-30 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "corporate",
            "0003_itemcollections_itemcolors_itemproperty_itemsizes_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="StoreGroups",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=250, verbose_name="Наименование группы"
                    ),
                ),
            ],
            options={
                "verbose_name": "Группа магазина",
                "verbose_name_plural": "Группы магазинов",
            },
        ),
        migrations.AlterModelOptions(
            name="cattree",
            options={"verbose_name": "Категория", "verbose_name_plural": "Категории"},
        ),
        migrations.CreateModel(
            name="Stores",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Как в 1С выгрузке",
                        max_length=250,
                        unique=True,
                        verbose_name="Наименование",
                    ),
                ),
                (
                    "chanel",
                    models.CharField(
                        choices=[
                            ("ONLINE", "Интернет-продажи"),
                            ("RETAIL", "Розничный магазин"),
                            ("WHOLESALE", "Оптовая торговля"),
                            ("COMM", "Комиссионные продажи"),
                        ],
                        default="RETAIL",
                        max_length=100,
                        verbose_name="Канал",
                    ),
                ),
                ("adress", models.TextField(null=True, verbose_name="Адрес")),
                (
                    "gr",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="corporate.storegroups",
                        verbose_name="Группа магазинов",
                    ),
                ),
            ],
            options={
                "verbose_name": "Магазин",
                "verbose_name_plural": "Магазины",
            },
        ),
    ]
