# Generated by Django 5.1.6 on 2025-05-30 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corporate", "0004_storegroups_alter_cattree_options_stores"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stores",
            name="adress",
            field=models.TextField(blank=True, null=True, verbose_name="Адрес"),
        ),
        migrations.AlterField(
            model_name="stores",
            name="chanel",
            field=models.CharField(
                choices=[
                    ("ONLINE", "Интернет-продажи"),
                    ("RETAIL", "Розничный магазин"),
                    ("WHOLESALE", "Оптовая торговля"),
                    ("COMM", "Комиссионные продажи"),
                    ("B2B", "B2B"),
                ],
                default="RETAIL",
                max_length=100,
                verbose_name="Канал",
            ),
        ),
    ]
