# Generated by Django 5.1.6 on 2025-05-30 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corporate", "0006_storegroups_pict_storegroups_region_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cattree",
            name="icon",
            field=models.TextField(
                blank=True,
                help_text="Скопируйте и вставьте svg код",
                null=True,
                verbose_name="Иконка",
            ),
        ),
    ]
