# Generated by Django 5.1.6 on 2025-05-30 13:38

import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corporate", "0007_cattree_icon"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemBrend",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250, verbose_name="Название")),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="bredlogos/",
                        verbose_name="Логотип",
                    ),
                ),
                (
                    "country",
                    django_countries.fields.CountryField(
                        default="RU", max_length=2, verbose_name="Страна"
                    ),
                ),
            ],
            options={
                "verbose_name": "Бренд",
                "verbose_name_plural": "Бренды",
            },
        ),
        migrations.CreateModel(
            name="ItemManufacturer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=250, verbose_name="Наименование производителя"
                    ),
                ),
                (
                    "country",
                    django_countries.fields.CountryField(
                        default="RU", max_length=2, verbose_name="Страна"
                    ),
                ),
            ],
            options={
                "verbose_name": "Производитель",
                "verbose_name_plural": "Производители",
            },
        ),
        migrations.CreateModel(
            name="ItemMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=250, verbose_name="Наименование материала"
                    ),
                ),
            ],
            options={
                "verbose_name": "Материал",
                "verbose_name_plural": "Материалы",
            },
        ),
        migrations.AddField(
            model_name="items",
            name="init_date",
            field=models.DateField(
                default=django.utils.timezone.now,
                help_text="Дата появления номенклатуры в ассортименте",
                verbose_name="Дата инициализации",
            ),
        ),
        migrations.AddField(
            model_name="items",
            name="brend",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="corporate.itembrend",
                verbose_name="Бренд",
            ),
        ),
        migrations.AddField(
            model_name="items",
            name="manufacturer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="corporate.itemmanufacturer",
                verbose_name="Производитель",
            ),
        ),
        migrations.AddField(
            model_name="items",
            name="material",
            field=models.ManyToManyField(
                to="corporate.itemmaterial", verbose_name="Материалы"
            ),
        ),
    ]
