# Generated by Django 5.1.6 on 2025-06-03 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corporate", "0008_itembrend_itemmanufacturer_itemmaterial_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemZones",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=250, unique=True, verbose_name="Наименование"
                    ),
                ),
            ],
            options={
                "verbose_name": "Доп сегментации",
                "verbose_name_plural": "Доп сегментации",
            },
        ),
        migrations.AddField(
            model_name="items",
            name="zones",
            field=models.ManyToManyField(
                to="corporate.itemzones", verbose_name="Доп сегментации"
            ),
        ),
    ]
