# Generated by Django 5.1.6 on 2025-06-04 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corporate", "0009_itemzones_items_zones"),
    ]

    operations = [
        migrations.AlterField(
            model_name="items",
            name="guid",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="1c id"
            ),
        ),
    ]
