# Generated by Django 5.1.6 on 2025-06-04 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corporate", "0010_alter_items_guid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="items",
            name="article",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="Артикль"
            ),
        ),
    ]
