# Generated by Django 5.1.6 on 2025-06-04 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corporate", "0011_alter_items_article"),
    ]

    operations = [
        migrations.AlterField(
            model_name="items",
            name="collection",
            field=models.ManyToManyField(
                blank=True, to="corporate.itemcollections", verbose_name="Коллекции"
            ),
        ),
        migrations.AlterField(
            model_name="items",
            name="colors",
            field=models.ManyToManyField(
                blank=True, to="corporate.itemcolors", verbose_name="Доступные цвета"
            ),
        ),
        migrations.AlterField(
            model_name="items",
            name="item_property",
            field=models.ManyToManyField(
                blank=True, to="corporate.itemproperty", verbose_name="Характеристики"
            ),
        ),
        migrations.AlterField(
            model_name="items",
            name="material",
            field=models.ManyToManyField(
                blank=True, to="corporate.itemmaterial", verbose_name="Материалы"
            ),
        ),
        migrations.AlterField(
            model_name="items",
            name="sizes",
            field=models.ManyToManyField(
                blank=True, to="corporate.itemsizes", verbose_name="Доступные размеры"
            ),
        ),
        migrations.AlterField(
            model_name="items",
            name="zones",
            field=models.ManyToManyField(
                blank=True, to="corporate.itemzones", verbose_name="Доп сегментации"
            ),
        ),
    ]
