# Generated by Django 5.1.6 on 2025-06-04 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corporate", "0013_subcategory_items_subcat"),
    ]

    operations = [
        migrations.AddField(
            model_name="subcategory",
            name="icon",
            field=models.TextField(
                blank=True,
                help_text="Скопируйте и вставьте svg код",
                null=True,
                verbose_name="Иконка",
            ),
        ),
    ]
