# Generated by Django 5.1.6 on 2025-08-17 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corporate", "0014_subcategory_icon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemmanufacturer",
            name="name",
            field=models.CharField(
                max_length=250, unique=True, verbose_name="Наименование производителя"
            ),
        ),
    ]
