# Generated by Django 5.1.6 on 2025-08-17 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corporate", "0015_alter_itemmanufacturer_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Agents",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Как в 1С выгрузке",
                        max_length=250,
                        unique=True,
                        verbose_name="Наименование",
                    ),
                ),
                (
                    "tel",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Телефон"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Почта"
                    ),
                ),
            ],
            options={
                "verbose_name": "Агент",
                "verbose_name_plural": "Агенты",
            },
        ),
        migrations.CreateModel(
            name="Managers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Как в 1С выгрузке",
                        max_length=250,
                        unique=True,
                        verbose_name="Наименование",
                    ),
                ),
                (
                    "tel",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Телефон"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Почта"
                    ),
                ),
            ],
            options={
                "verbose_name": "Менеджер",
                "verbose_name_plural": "Менеджеры",
            },
        ),
    ]
