# Generated by Django 5.1.6 on 2025-08-17 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corporate", "0016_agents_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="agents",
            name="report_name",
            field=models.CharField(
                blank=True,
                help_text="Как в отчете показывать",
                max_length=250,
                null=True,
                unique=True,
                verbose_name="Имя в отчете",
            ),
        ),
        migrations.AddField(
            model_name="managers",
            name="report_name",
            field=models.CharField(
                blank=True,
                help_text="Как в отчете показывать",
                max_length=250,
                null=True,
                unique=True,
                verbose_name="Имя в отчете",
            ),
        ),
        migrations.AlterField(
            model_name="managers",
            name="name",
            field=models.CharField(
                help_text="Как в 1С выгрузке",
                max_length=250,
                unique=True,
                verbose_name="Имя в 1С",
            ),
        ),
    ]
