# Generated by Django 5.1.6 on 2025-08-17 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corporate", "0017_agents_report_name_managers_report_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="items",
            name="im_id",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="im id"
            ),
        ),
        migrations.AddField(
            model_name="items",
            name="onec_cat",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="Группа номенклатуры 1С",
            ),
        ),
        migrations.AddField(
            model_name="items",
            name="onec_subcat",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="Вид номенклатуры 1С",
            ),
        ),
        migrations.AlterField(
            model_name="items",
            name="name",
            field=models.CharField(
                max_length=200, verbose_name="Название товара на сайте"
            ),
        ),
    ]
