# Generated by Django 5.1.6 on 2025-08-18 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corporate", "0018_items_im_id_items_onec_cat_items_onec_subcat_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="items",
            name="fullname",
            field=models.CharField(
                max_length=250, unique=True, verbose_name="Наименование 1С"
            ),
        ),
    ]
