# Generated by Django 5.1.6 on 2025-09-30 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corporate", "0019_alter_items_fullname"),
    ]

    operations = [
        migrations.AddField(
            model_name="cattree",
            name="comments",
            field=models.TextField(blank=True, null=True, verbose_name="Комментарий"),
        ),
        migrations.AddField(
            model_name="subcategory",
            name="comments",
            field=models.TextField(blank=True, null=True, verbose_name="Комментарий"),
        ),
    ]
