# Generated by Django 5.1.6 on 2026-01-27 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corporate", "0020_cattree_comments_subcategory_comments"),
    ]

    operations = [
        migrations.CreateModel(
            name="Barcode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("barcode", models.CharField(max_length=50, verbose_name="Штрихкод")),
            ],
            options={
                "verbose_name": "Штрихкод",
                "verbose_name_plural": "Штрихкоды",
            },
        ),
        migrations.AddField(
            model_name="items",
            name="barcode",
            field=models.ManyToManyField(
                blank=True, to="corporate.barcode", verbose_name="Штрихкод"
            ),
        ),
    ]
