# Generated by Django 5.1.6 on 2026-01-27 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corporate", "0021_barcode_items_barcode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="barcode",
            name="barcode",
            field=models.CharField(max_length=50, unique=True, verbose_name="Штрихкод"),
        ),
    ]
