# Generated by Django 5.1.6 on 2026-02-21 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate', '0022_alter_barcode_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmanufacturer',
            name='report_name',
            field=models.CharField(blank=True, help_text='Как в отчетах показывать производителя', max_length=250, null=True, verbose_name='Название в отчете'),
        ),
    ]
