# Generated by Django 5.1.6 on 2026-03-02 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate', '0023_itemmanufacturer_report_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='storegroups',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активная группа'),
        ),
        migrations.AlterField(
            model_name='items',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='corporate.itemmanufacturer', verbose_name='Производитель'),
        ),
    ]
