# Generated by Django 5.1.6 on 2026-04-11 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corporate", "0024_storegroups_is_active_alter_items_manufacturer"),
    ]

    operations = [
        migrations.AddField(
            model_name="barcode",
            name="spec",
            field=models.TextField(blank=True, null=True, verbose_name="Штрихкод"),
        ),
    ]
