# Generated by Django 5.1.6 on 2025-06-08 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SalesDash",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отчёт по продажам",
                "verbose_name_plural": "Отчёт по продажам",
                "managed": False,
                "default_permissions": (),
            },
        ),
    ]
