# Generated by Django 5.1.6 on 2025-06-08 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CatDash",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отчёт по категориям",
                "verbose_name_plural": "чёт по категориям",
                "managed": False,
                "default_permissions": (),
            },
        ),
    ]
