# Generated by Django 5.1.6 on 2025-08-17 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_catdash"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="catdash",
            options={
                "default_permissions": (),
                "managed": False,
                "verbose_name": "Сегментный анализ",
                "verbose_name_plural": "Сегментный анализ",
            },
        ),
    ]
