# Generated by Django 5.1.6 on 2025-09-14 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_alter_catdash_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="SalesReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сегментный анализ",
                "verbose_name_plural": "Сегментный анализ",
                "managed": False,
                "default_permissions": (),
            },
        ),
    ]
