# Generated by Django 5.1.6 on 2025-09-14 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0004_salesreport"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="salesreport",
            options={
                "managed": False,
                "verbose_name": "Отчет анализ",
                "verbose_name_plural": "Отчет анализ",
            },
        ),
    ]
