# Generated by Django 5.1.6 on 2025-09-15 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0005_alter_salesreport_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="salesreport",
            options={
                "default_permissions": ("view",),
                "managed": False,
                "verbose_name": "Панель продаж",
                "verbose_name_plural": "Панель продаж",
            },
        ),
    ]
