# Generated by Django 5.1.6 on 2025-09-30 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0006_alter_salesreport_options"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CatDash",
        ),
        migrations.DeleteModel(
            name="SalesDash",
        ),
    ]
