"""
Django settings for fr project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv
# Загружаем .env
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'fallback_secret_key')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True')

ALLOWED_HOSTS = ['127.0.0.1','localhost','37.46.129.233']

DATA_UPLOAD_MAX_NUMBER_FIELDS = 50000

# Application definition

INSTALLED_APPS = [
    "jazzmin",
    'django_mptt_admin', 
    'django_plotly_dash.apps.DjangoPlotlyDashConfig',    
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corporate",
    "sales",
    "dashboard",
    "budgets"
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "fr.urls"

#BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "fr.wsgi.application"

X_FRAME_OPTIONS = 'ALLOWALL'

JAZZMIN_SETTINGS = {

    "site_title": "FR COSMO PORTAL",
    "site_header": "FR ADMIN",
    "site_brand": "Панель управления",
    "site_logo": "/img/login_avatar.png",
    "site_favicon": "/img/frlogo-small.png",
    "welcome_sign": "Добро пожаловать в панель управления",
    "show_ui_builder": True,
    "navigation_expanded": False,
    # "search_model": "auth.User",
    "user_avatar": False,
    "custom_css": "css/custom.css",
    #"hide_apps": ['scr'],
    #"hide_models": ['rr.cart'],
    
    "topmenu_links": [
        # стандартные ссылки
        {"name": "Home", },
        {"model": "auth.User"},
        {"model": "sales.MV_Daily_Sales"},
        # ссылка на Dash Upload Form
        {"name": "Upload Form", "url": "/upload-form", "new_window": True},
        {"name": "Redis update", "url": "/redis-form", "new_window": True},
    ],
    



        # App with dropdown menu to all its models pages (Permissions checked against models)
        #{"app": "rr"},
    #     {"model": "rr.cart"},

        # external url that opens in a new window (Permissions can be added)
    #    {"name": "Помощь", "url": "https://github.com/farridav/django-jazzmin/issues", "new_window": True},

    #],


    "custom_js": "js/custom.js",
    "show_collapse": True,
    "related_modal_active": True,
    "icons": {
         "auth": "fa fa-users",
         "auth.user": "fa fa-user",
         "auth.Group": "fa fa-users",
         "corporate": "fa fa-book",
         "budgets":"fa-piggy-bank",
         
        ### --- ДЭШБОАРД --- 
        "dashboard": "fa-solid fa-gauge-high",
        "dashboard.SalesReport": "fa-solid fa-chart-line",
        
         
        ### --- ПРОДАЖИ --- 
        "sales": "fa-solid fa-chart-column",
        "sales.MV_Daily_Sales": "fa-solid fa-calendar-day",
        "sales.MVSalesOrder": "fa-solid fa-truck-fast",
        
        ### --- СПРАВОЧНИКИ --- 
        "corporate": "fa-solid fa-book",
          
        "corporate.Companies": "fa-solid fa-building",
        "corporate.Projects": "fa-solid fa-diagram-project",

        "corporate.ItemMaterial": "fa-solid fa-layer-group",
        "corporate.ItemManufacturer": "fa-solid fa-industry",
        "corporate.ItemBrend": "fa-solid fa-copyright",

        "corporate.ItemProperty": "fa-solid fa-sliders",
        "corporate.ItemColors": "fa-solid fa-palette",
        "corporate.ItemSizes": "fa-solid fa-ruler-combined",
        "corporate.ItemZones": "fa-solid fa-tags",
        "corporate.ItemCollections": "fa-solid fa-cubes",

        "corporate.CatTree": "fa-solid fa-folder-tree",
        "corporate.SubCategory": "fa-solid fa-folder-open",

        "corporate.Barcode": "fa-solid fa-barcode",
        "corporate.Items": "fa-solid fa-box-open",

        "corporate.StoreGroups": "fa-solid fa-object-group",
        "corporate.Stores": "fa-solid fa-store",

        "corporate.Managers": "fa-solid fa-user-tie",
        "corporate.Agents": "fa-solid fa-user-gear",
        
        
         ### --- БЮДЖЕТИРОВАНИЕ --- 
         "budgets": "fa-solid fa-coins",
        "budgets.ForecastTypes": "fa-solid fa-code-branch",
        "budgets.ForecastSubjects": "fa-solid fa-sitemap",

        "budgets.Forecasts": "fa-solid fa-file-invoice-dollar",
        "budgets.ForecastData": "fa-solid fa-table-cells",


     },
    "default_icon_parents": "fa fa-fw fa-folder",
    "default_icon_children": "fa fa-fw fa-file",
    "changeform_format": "collapsed",
    "order_with_respect_to": [
        'dashboard',       # Дэшбоард 
        'sales',           # Продажи 
        'corporate',       # Справочники 
        "budgets",         # Бюджетирование
        "auth",            # Пользователи и группы
        "services",        # Служебные — всегда в конце
    ],

    # "changeform_format_overrides": {"auth.user": "vertical_tabs",},

}




JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": True,
    "footer_small_text": True,

    # текст в контенте лучше обычный размер,
    # так легче читать списки и таблицы
    "body_small_text": False,

    # логотип можно оставить мелким
    "brand_small_text": True,
    "brand_colour": "navbar-secondary",
    "accent": "accent-info",
    "navbar": "navbar-secondary navbar-dark",
    "no_navbar_border": False,

    # удобно, когда верхнее меню фиксировано
    "navbar_fixed": True,

    "layout_boxed": False,
    "footer_fixed": False,

    # фиксируем сайдбар, чтобы меню не уезжало
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-primary",

    # меню слева чуть крупнее
    "sidebar_nav_small_text": False,

    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,

    "sidebar_nav_compact_style": True,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": True,

    "theme": "yeti", 
    "dark_mode_theme": None,

    "button_classes": {
        "primary": "btn-outline-primary",
        "secondary": "btn-outline-secondary",
        "info": "btn-outline-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success",
    },
    "actions_sticky_top": False,
}




# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": os.getenv('DB_ENGINE',"django.db.backends.mysql"),
        "NAME": os.getenv('DB_NAME', 'djangodb'),  # Здесь имя базы данных, которую ты хочешь создать
        "USER": os.getenv('DB_USER', 'django_user'), # Пользователь MySQL
        "PASSWORD": os.getenv('DB_PASSWORD', 'strong_password'),  # Пароль MySQL
        "HOST": os.getenv('DB_HOST', 'localhost'),  # Или другой IP, если база не локальная
        "PORT": os.getenv('DB_PORT', '3306'),  # Порт для MySQL
        'OPTIONS': {
            'charset': 'utf8mb4',
            # ⏱ таймауты соединения и выполнения запросов
            "connect_timeout": 60,     # соединиться с БД
            "read_timeout": 300,       # ждать результат SELECT
            "write_timeout": 300,      # ждать INSERT/UPDATE
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

from django.conf.locale.ru import formats as ru_formats

LANGUAGE_CODE = "ru"
LANGUAGES = [
    ("en", "English"),
    ("ru", "Русский"),
]

ru_formats.DECIMAL_SEPARATOR = "."
ru_formats.THOUSAND_SEPARATOR = ","
USE_THOUSAND_SEPARATOR = True
TIME_ZONE = "Europe/Moscow"

USE_I18N = True
USE_L10N = True
USE_TZ = False



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"

STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

import redis

# Подключение к Redis
REDIS_CLIENT = redis.Redis(
    host=os.getenv('REDIS_CLIENT_HOST',""),
    port=os.getenv('REDIS_CLIENT_PORT',""),
    db=os.getenv('REDIS_CLIENT_DB',""),
    password=os.getenv('REDIS_CLIENT_PSW',""),
    decode_responses=False  # Оставляем False для работы с pickle
)

SALES_REPORT_KEY = 'super-secret-key'