"""
Django settings for fr project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-h4-hmo1y3583*_fcs4on^l-bxdd#%#b@ed(53g9mq37u_$#1*e"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

DATA_UPLOAD_MAX_NUMBER_FIELDS = 50000

# Application definition

INSTALLED_APPS = [
    "jazzmin",
    'django_mptt_admin', 
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corporate",
    "sales",
    "dashboard"
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "fr.urls"

#BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "fr.wsgi.application"

X_FRAME_OPTIONS = 'ALLOWALL'

JAZZMIN_SETTINGS = {

    "site_title": "FR COSMO PORTAL",
    "site_header": "FR ADMIN",
    "site_brand": "Панель управления",
    "site_logo": "/img/frlogo-small.png",
    "site_favicon": "/img/frlogo-small.png",
    "welcome_sign": "Добро пожаловать в панель управления",
    "show_ui_builder": True,
    "navigation_expanded": False,
    "search_model": "auth.User",
    "user_avatar": False,
    "custom_css": "css/custom.css",
    #"hide_apps": ['scr'],
    #"hide_models": ['rr.cart'],
    #"topmenu_links": [

        # Url that gets reversed (Permissions can be added)
    #    {"name": "Home",  "url": "admin:index", "permissions": ["auth.view_user"]},

        # model admin to link to (Permissions checked against model)
    #    {"model": "auth.User"},

        # App with dropdown menu to all its models pages (Permissions checked against models)
        #{"app": "rr"},
    #     {"model": "rr.cart"},

        # external url that opens in a new window (Permissions can be added)
    #    {"name": "Помощь", "url": "https://github.com/farridav/django-jazzmin/issues", "new_window": True},

    #],

    #"custom_js": None,
    "show_collapse": True,
    "related_modal_active": True,
    "icons": {
         "auth": "fa fa-users",
         "auth.user": "fa fa-user",
         "auth.Group": "fa fa-users",
         "corporate": "fa fa-book",
    #     "rr": "fa fa-building",
    #     "rr.Properties": "fa fa-landmark",
    #     "rr.Premisses": "fa fa-door-open",
    #     "rr.PremissesTypes": "fa fa-tags",
    #     "rr.Floors": "fa fa-bars",
    #     "rr.PremissStructure": "fa fa-project-diagram",
    #     "rr.SupportDocuments":"fa fa-map",
    #     "rr.Acts":"fa fa-hammer",
    #     "contragents": "fa fa-address-book",
    #     "scr": "fa fa-bug",
    #     "la": "fa fa-handshake-simple",
    #     "treasury": "fa fa-money-bill",
    #     "dashboard":"fa fa-tachometer-alt",
    #     "dashboard.ReportAR":"fa fa-hand-holding-usd",
    #     #"corporate.owners": "fa fa-building",
    #     #"corporate.bankaccount": "fa fa-money",
     },
    "default_icon_parents": "fa fa-fw fa-folder",
    "default_icon_children": "fa fa-fw fa-file",
    "changeform_format": "collapsed",
    # "order_with_respect_to": ["rr.Properties", "rr.Premisses", "rr.PremissesTypes", "rr.Floors", "rr.PremissesStatus", "rr.PremissesUsage", "rr.SupportDocuments"],

    # "changeform_format_overrides": {"auth.user": "vertical_tabs",},

}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": True,
    "footer_small_text": True,
    "body_small_text": True,
    "brand_small_text": True,
    #"brand_colour": "navbar-lightblue",
    #"accent": "accent-primary",
    #"navbar": "navbar-lightblue navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": False,
    #"sidebar": "sidebar-light-success",
    "sidebar_nav_small_text": True,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": True,
    "sidebar_nav_legacy_style": True,
    "sidebar_nav_flat_style": False,
    "theme": "pulse",
    #"dark_mode": True,
    #"dark_mode_theme": True,
    "button_classes": {
        "primary": "btn-outline-primary",
        "secondary": "btn-outline-secondary",
        "info": "btn-outline-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success",
    },
    "actions_sticky_top": True,

}




# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": "cosmo",  # Здесь имя базы данных, которую ты хочешь создать
        "USER": "root",  # Пользователь MySQL
        "PASSWORD": "",  # Пароль MySQL
        "HOST": "127.0.0.1",  # Или другой IP, если база не локальная
        "PORT": "3306",  # Порт для MySQL
        'OPTIONS': {
            'charset': 'utf8mb4',
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

from django.conf.locale.ru import formats as ru_formats

LANGUAGE_CODE = "ru"
LANGUAGES = [
    ("en", "English"),
    ("ru", "Русский"),
]

ru_formats.DECIMAL_SEPARATOR = "."
ru_formats.THOUSAND_SEPARATOR = ","
USE_THOUSAND_SEPARATOR = True
TIME_ZONE = "Europe/Moscow"

USE_I18N = True
USE_L10N = True
USE_TZ = False



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"

STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

import redis

# Подключение к Redis
REDIS_CLIENT = redis.Redis(
    host="localhost",
    port=6379,
    db=0,
    decode_responses=False  # Оставляем False для работы с pickle
)
