# Generated by Django 5.1.6 on 2025-10-20 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("corporate", "0020_cattree_comments_subcategory_comments"),
    ]

    operations = [
        migrations.CreateModel(
            name="Forecasts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_by",
                    models.CharField(
                        blank=True, max_length=250, null=True, verbose_name="Кем создан"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                ("start_date", models.DateField(verbose_name="Дата начала")),
                ("end_date", models.DateField(verbose_name="Дата окончания")),
                (
                    "parameters",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Параметры модели"
                    ),
                ),
                (
                    "comments",
                    models.TextField(blank=True, null=True, verbose_name="Комментарии"),
                ),
            ],
            options={
                "verbose_name": "Бюджет",
                "verbose_name_plural": "Бюджеты",
            },
        ),
        migrations.CreateModel(
            name="ForecastSubjects",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=205, verbose_name="Раздел бюджета"),
                ),
            ],
            options={
                "verbose_name": "Раздел бюджета",
                "verbose_name_plural": "Разделы бюджетов",
            },
        ),
        migrations.CreateModel(
            name="ForecastTypes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250, verbose_name="Тип бюджета")),
            ],
            options={
                "verbose_name": "Тип бюджета",
                "verbose_name_plural": "Типы бюджетов",
            },
        ),
        migrations.CreateModel(
            name="ForecastData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Дата")),
                (
                    "dt",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="dt"
                    ),
                ),
                (
                    "cr",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="cr"
                    ),
                ),
                (
                    "subaccount",
                    models.CharField(
                        blank=True, max_length=250, null=True, verbose_name="Субсчет"
                    ),
                ),
                (
                    "cat",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="corporate.cattree",
                        verbose_name="Категория",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="corporate.storegroups",
                        verbose_name="Магазин",
                    ),
                ),
                (
                    "forecast",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forecast_data",
                        to="budgets.forecasts",
                        verbose_name="Бюджет",
                    ),
                ),
            ],
            options={
                "verbose_name": "Данные",
                "verbose_name_plural": "Данные",
            },
        ),
        migrations.AddField(
            model_name="forecasts",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="forecasts",
                to="budgets.forecastsubjects",
                verbose_name="Раздел бюджета",
            ),
        ),
        migrations.AddField(
            model_name="forecasts",
            name="tp",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="forecasts",
                to="budgets.forecasttypes",
                verbose_name="Тип бюджета",
            ),
        ),
    ]
