# Generated by Django 5.1.6 on 2026-04-07 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                (
                    "fullname",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="Наименование",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        blank=True, max_length=250, null=True, verbose_name="Номер"
                    ),
                ),
                (
                    "date_from",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "update_at",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата изменения"
                    ),
                ),
                (
                    "is_cancelled",
                    models.BooleanField(default=False, verbose_name="Отмененный заказ"),
                ),
                (
                    "сancellation_reason",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Причина отмены",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="Статус"
                    ),
                ),
            ],
            options={
                "verbose_name": "Заказ",
                "verbose_name_plural": "Заказы",
            },
        ),
    ]
