# Generated by Django 5.1.6 on 2026-04-07 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="сancellation_reason",
            new_name="cancellation_reason",
        ),
    ]
