# Generated by Django 5.1.6 on 2026-04-07 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_rename_сancellation_reason_order_cancellation_reason"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="id",
            field=models.CharField(max_length=36, primary_key=True, serialize=False),
        ),
    ]
