# Generated by Django 5.1.6 on 2026-04-11 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corporate", "0025_barcode_spec"),
        ("orders", "0003_alter_order_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fullname",
                    models.CharField(
                        max_length=500, verbose_name="Наименование в заказе"
                    ),
                ),
                (
                    "order_barcode",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Наименование в заказе",
                    ),
                ),
                (
                    "order_article",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Наименование в заказе",
                    ),
                ),
                (
                    "qty",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Количество",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="Цена"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="Сумма"
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="corporate.items",
                        verbose_name="Номенклатура",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="orders.order",
                        verbose_name="Заказ",
                    ),
                ),
            ],
            options={
                "verbose_name": "Состав заказа",
                "verbose_name_plural": "Состав заказов",
            },
        ),
    ]
