# Generated by Django 5.1.6 on 2026-04-14 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corporate", "0025_barcode_spec"),
        ("orders", "0004_orderitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="fullname",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="order_article",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="order_barcode",
        ),
        migrations.AddField(
            model_name="order",
            name="client",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="Статус"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="manager",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="Статус"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="oper_type",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="Статус"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="store",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="Статус"
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="barcode",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="corporate.barcode",
                verbose_name="Номенклатура",
            ),
        ),
    ]
