# Generated by Django 5.1.6 on 2026-04-15 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_remove_orderitem_fullname_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrdersCF",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_guid",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="GUID"
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата операции"
                    ),
                ),
                (
                    "oper_type",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        null=True,
                        verbose_name="Тип операции",
                    ),
                ),
                (
                    "oper_name",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        null=True,
                        verbose_name="Название операции",
                    ),
                ),
                (
                    "cash_deck",
                    models.CharField(
                        blank=True, max_length=300, null=True, verbose_name="Касса"
                    ),
                ),
                (
                    "doc_number",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        null=True,
                        verbose_name="Номер документа",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="Сумма"
                    ),
                ),
                (
                    "store",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        null=True,
                        verbose_name="Подразделение",
                    ),
                ),
                (
                    "register",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        null=True,
                        verbose_name="Регистратор",
                    ),
                ),
            ],
            options={
                "verbose_name": "Оплата заказов",
                "verbose_name_plural": "Оплаты заказов",
            },
        ),
    ]
