# Generated by Django 5.1.6 on 2026-04-17 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_orderscf"),
    ]

    operations = [
        migrations.CreateModel(
            name="MV_Orders",
            fields=[
                (
                    "order_id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                (
                    "order_name",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="Наименование",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Номер"
                    ),
                ),
                (
                    "date_from",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "update_at",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата обновления"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Стаутус заказа",
                    ),
                ),
                (
                    "change_status",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Стаутус изменения",
                    ),
                ),
                (
                    "client",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="Клиент"
                    ),
                ),
                (
                    "manager",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="Менеджер"
                    ),
                ),
                (
                    "store",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="Магазин"
                    ),
                ),
                (
                    "qty_ordered",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Количество заказано",
                    ),
                ),
                (
                    "qty_cancelled",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Количество отмененно",
                    ),
                ),
                (
                    "order_qty",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Количество финальное",
                    ),
                ),
                (
                    "order_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Сумма заказа",
                    ),
                ),
                (
                    "amount_delivery",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="В т.ч стоимость услуг",
                    ),
                ),
                (
                    "amount_cancelled",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Сумма отмен",
                    ),
                ),
                (
                    "amount_active",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Финальная сумма",
                    ),
                ),
                (
                    "cash_recieved",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Посутпления денег",
                    ),
                ),
                (
                    "cash_returned",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Возвраты денег",
                    ),
                ),
                (
                    "cash_pmts",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Всего оплачено",
                    ),
                ),
                (
                    "shiped",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Отгружено",
                    ),
                ),
                (
                    "returned",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Возвращено",
                    ),
                ),
                (
                    "shiped_qty",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Фианально отгружено",
                    ),
                ),
                (
                    "shiped_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Реализация",
                    ),
                ),
                (
                    "returned_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Возвраты",
                    ),
                ),
                (
                    "total_shiped_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Итого реализация",
                    ),
                ),
                (
                    "shiped_delivery_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="В т.ч реализация услуг",
                    ),
                ),
                (
                    "payment_dates",
                    models.TextField(
                        blank=True, null=True, verbose_name="Даты и суммы оплат"
                    ),
                ),
            ],
            options={
                "verbose_name": "Заказ информация",
                "verbose_name_plural": "Заказы информация",
                "db_table": "mv_orders_summary_table",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="MV_Orders_Items",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.AlterModelOptions(
            name="orderscf",
            options={
                "managed": False,
                "verbose_name": "Оплата заказов",
                "verbose_name_plural": "Оплаты заказов",
            },
        ),
        migrations.AlterField(
            model_name="order",
            name="client",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="Клиент"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="manager",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="Менеджер"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="oper_type",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="Тип заказа"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="store",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="Магазин"
            ),
        ),
    ]
