# Generated by Django 5.1.6 on 2026-04-17 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0007_mv_orders_mv_orders_items_alter_orderscf_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MV_OrdersItems",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fullname",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        null=True,
                        verbose_name="Номенклатура",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        null=True,
                        verbose_name="Название в ИМ",
                    ),
                ),
                (
                    "article",
                    models.CharField(
                        blank=True, max_length=300, null=True, verbose_name="Артикль"
                    ),
                ),
                (
                    "barcode",
                    models.CharField(
                        blank=True, max_length=300, null=True, verbose_name="Штрихкод"
                    ),
                ),
                (
                    "qty",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Кол-во",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="Цена"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="Сумма"
                    ),
                ),
                (
                    "cancellation_reason",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        null=True,
                        verbose_name="Причина отмены",
                    ),
                ),
                (
                    "parent_cat",
                    models.CharField(
                        blank=True, max_length=300, null=True, verbose_name="Группа"
                    ),
                ),
                (
                    "cat",
                    models.CharField(
                        blank=True, max_length=300, null=True, verbose_name="Категория"
                    ),
                ),
                (
                    "subcat",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        null=True,
                        verbose_name="Подкатегоря",
                    ),
                ),
                (
                    "warehouse",
                    models.CharField(
                        blank=True, max_length=300, null=True, verbose_name="Склад"
                    ),
                ),
            ],
            options={
                "verbose_name": "Состав заказа",
                "verbose_name_plural": "Состав заказов",
                "db_table": "orders_orderscf",
                "managed": False,
            },
        ),
        migrations.DeleteModel(
            name="MV_Orders_Items",
        ),
        migrations.AlterModelTable(
            name="orderscf",
            table="orders_orderscf",
        ),
    ]
