# Generated by Django 5.1.6 on 2026-04-17 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0008_mv_ordersitems_delete_mv_orders_items_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="orderscf",
            table="mv_orders_items",
        ),
    ]
