# Generated by Django 5.1.6 on 2026-04-17 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0009_alter_orderscf_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="mv_ordersitems",
            table="mv_orders_items",
        ),
        migrations.AlterModelTable(
            name="orderscf",
            table="orders_orderscf",
        ),
    ]
