# Generated by Django 5.1.6 on 2025-06-02 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("corporate", "0008_itembrend_itemmanufacturer_itemmaterial_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SalesData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Дата")),
                (
                    "operation",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Sales", "Продажа"),
                            ("Return", "Возврат"),
                            ("Other", "Прочее"),
                        ],
                        max_length=100,
                        null=True,
                        verbose_name="Тип операций",
                    ),
                ),
                (
                    "dt",
                    models.DecimalField(
                        decimal_places=2, default=0.0, max_digits=12, verbose_name="Дт"
                    ),
                ),
                (
                    "cr",
                    models.DecimalField(
                        decimal_places=2, default=0.0, max_digits=12, verbose_name="Кр"
                    ),
                ),
                (
                    "quant_dt",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=12,
                        verbose_name="Количество_Дт",
                    ),
                ),
                (
                    "quant_cr",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=12,
                        verbose_name="Количество_Кр",
                    ),
                ),
                (
                    "amount_undisc",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=12,
                        verbose_name="Сумма без скидки",
                    ),
                ),
                (
                    "discount_auto",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=12,
                        verbose_name="Скидка автомат",
                    ),
                ),
                (
                    "discount_design",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=12,
                        verbose_name="Скидка дизайнер",
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=12,
                        verbose_name="Размер скидки",
                    ),
                ),
                (
                    "discount_percent_auto",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=12,
                        verbose_name="Процент скидки автомат",
                    ),
                ),
                (
                    "discount_percent_design",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=12,
                        verbose_name="Процент скидки дизайнер",
                    ),
                ),
                (
                    "diccount_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=12,
                        verbose_name="Процент скидки",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="corporate.items",
                        verbose_name="Наименование",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="corporate.stores",
                        verbose_name="Точка продаж",
                    ),
                ),
            ],
            options={
                "verbose_name": "Данные продаж",
                "verbose_name_plural": "Данные продаж",
            },
        ),
    ]
