# Generated by Django 5.1.6 on 2025-06-02 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salesdata",
            name="amount_undisc",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Сумма без скидки",
            ),
        ),
        migrations.AlterField(
            model_name="salesdata",
            name="diccount_percent",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Процент скидки",
            ),
        ),
        migrations.AlterField(
            model_name="salesdata",
            name="discount_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Размер скидки",
            ),
        ),
        migrations.AlterField(
            model_name="salesdata",
            name="discount_auto",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Скидка автомат",
            ),
        ),
        migrations.AlterField(
            model_name="salesdata",
            name="discount_design",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Скидка дизайнер",
            ),
        ),
        migrations.AlterField(
            model_name="salesdata",
            name="discount_percent_auto",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Процент скидки автомат",
            ),
        ),
        migrations.AlterField(
            model_name="salesdata",
            name="discount_percent_design",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Процент скидки дизайнер",
            ),
        ),
    ]
