# Generated by Django 5.1.6 on 2025-08-19 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corporate", "0019_alter_items_fullname"),
        ("sales", "0002_alter_salesdata_amount_undisc_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesdata",
            name="agent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="corporate.agents",
                verbose_name="Агент",
            ),
        ),
        migrations.AddField(
            model_name="salesdata",
            name="client_order",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Описание"
            ),
        ),
        migrations.AddField(
            model_name="salesdata",
            name="client_order_date",
            field=models.DateField(blank=True, null=True, verbose_name="Дата заказа"),
        ),
        migrations.AddField(
            model_name="salesdata",
            name="client_order_number",
            field=models.CharField(
                blank=True, max_length=600, null=True, verbose_name="Характеристика"
            ),
        ),
        migrations.AddField(
            model_name="salesdata",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="corporate.managers",
                verbose_name="Менеджер",
            ),
        ),
        migrations.AddField(
            model_name="salesdata",
            name="warehouse",
            field=models.CharField(
                blank=True, max_length=600, null=True, verbose_name="Склад"
            ),
        ),
    ]
