# Generated by Django 5.1.6 on 2025-08-19 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corporate", "0019_alter_items_fullname"),
        ("sales", "0003_salesdata_agent_salesdata_client_order_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salesdata",
            name="store",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="corporate.stores",
                verbose_name="Точка продаж",
            ),
        ),
    ]
