# Generated by Django 5.1.6 on 2025-08-19 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0004_alter_salesdata_store"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesdata",
            name="spec",
            field=models.CharField(
                blank=True, max_length=600, null=True, verbose_name="Харектеристика"
            ),
        ),
        migrations.AlterField(
            model_name="salesdata",
            name="warehouse",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="Склад"
            ),
        ),
    ]
