# Generated by Django 5.1.6 on 2025-08-19 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0005_salesdata_spec_alter_salesdata_warehouse"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salesdata",
            name="spec",
            field=models.TextField(
                blank=True, null=True, verbose_name="Харектеристика"
            ),
        ),
    ]
