# Generated by Django 5.1.6 on 2026-01-29 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0006_alter_salesdata_spec"),
    ]

    operations = [
        migrations.CreateModel(
            name="MV_Daily_Sales",
            fields=[
                (
                    "date",
                    models.DateField(
                        primary_key=True, serialize=False, verbose_name="Дата"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Выручка",
                    ),
                ),
                (
                    "quant",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Кол-во товаров",
                    ),
                ),
                (
                    "orders",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Кол-во заказов"
                    ),
                ),
                (
                    "ave_check",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Ср чек",
                    ),
                ),
                (
                    "dt",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Продажи",
                    ),
                ),
                (
                    "cr",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Возвраты",
                    ),
                ),
                (
                    "rtr_ratio",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="К возвратов",
                    ),
                ),
                (
                    "quant_dt",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Кол-во продано",
                    ),
                ),
                (
                    "quant_cr",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Кол-во возвращено",
                    ),
                ),
            ],
            options={
                "verbose_name": "Дневные продажи",
                "verbose_name_plural": "Дневные продажи",
                "db_table": "mv_daily_sales",
                "managed": False,
            },
        ),
    ]
