# Generated by Django 5.1.6 on 2026-01-30 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corporate", "0022_alter_barcode_barcode"),
        ("sales", "0007_mv_daily_sales"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesdata",
            name="barcode",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="corporate.barcode",
                verbose_name="Баркод",
            ),
        ),
    ]
