# Generated by Django 5.1.6 on 2026-02-14 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0008_salesdata_barcode"),
    ]

    operations = [
        migrations.CreateModel(
            name="SalesOrders",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "client_order",
                    models.CharField(
                        max_length=250, unique=True, verbose_name="Заказ клиента"
                    ),
                ),
                (
                    "client_order_date",
                    models.DateField(blank=True, null=True, verbose_name="Дата заказа"),
                ),
                (
                    "client_order_number",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=250,
                        null=True,
                        verbose_name="Номер заказа клиента",
                    ),
                ),
                (
                    "client_order_type",
                    models.CharField(
                        blank=True, max_length=250, null=True, verbose_name="Тип заказа"
                    ),
                ),
                (
                    "salesdata",
                    models.ManyToManyField(
                        blank=True, related_name="orders", to="sales.salesdata"
                    ),
                ),
            ],
        ),
    ]
