# Generated by Django 5.1.6 on 2026-02-14 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0009_salesorders"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salesorders",
            name="client_order",
            field=models.CharField(max_length=250, verbose_name="Заказ клиента"),
        ),
        migrations.AddConstraint(
            model_name="salesorders",
            constraint=models.UniqueConstraint(
                fields=("client_order", "client_order_date", "client_order_number"),
                name="uniq_sales_order_combo",
            ),
        ),
    ]
