# Generated by Django 5.1.6 on 2026-02-14 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0010_alter_salesorders_client_order_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MVSalesOrder",
            fields=[
                (
                    "salesorders_id",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                (
                    "client_order_type",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        verbose_name="Тип заказов",
                    ),
                ),
                (
                    "client_order",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="Заказ"
                    ),
                ),
                (
                    "client_order_number",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Номер заказа",
                    ),
                ),
                (
                    "client_order_date",
                    models.DateField(blank=True, null=True, verbose_name="Дата заказа"),
                ),
                (
                    "order_min_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Первая отгрузка"
                    ),
                ),
                (
                    "order_max_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Последняя отгрузка"
                    ),
                ),
                (
                    "order_duration",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Срок реализации"
                    ),
                ),
                (
                    "sales",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Сумма продаж",
                    ),
                ),
                (
                    "returns",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Сумма возвратов",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Сумма заказа",
                    ),
                ),
                (
                    "items_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Стоимость товара",
                    ),
                ),
                (
                    "service_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Стоимость услуг",
                    ),
                ),
                (
                    "items_quant",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Количество мест в заказе",
                    ),
                ),
                (
                    "unique_items",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Кол-во номенклатур",
                    ),
                ),
                (
                    "manager_name",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="Менеджеры"
                    ),
                ),
            ],
            options={
                "verbose_name": "Заказ",
                "verbose_name_plural": "Заказы",
                "db_table": "mv_orders",
                "managed": False,
            },
        ),
    ]
