# Generated by Django 5.1.6 on 2026-02-14 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0011_mvsalesorder"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="salesorders",
            name="client_order_number",
        ),
    ]
