# Generated by Django 5.1.6 on 2026-02-14 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0012_remove_salesorders_client_order_number"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="salesorders",
            constraint=models.UniqueConstraint(
                fields=("client_order", "client_order_date"),
                name="uniq_sales_order_combo",
            ),
        ),
    ]
