# Generated by Django 5.1.6 on 2026-02-14 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0013_remove_salesorders_uniq_sales_order_combo_and_more"),
    ]

    operations = [
    migrations.AddField(
        model_name="salesorders",
        name="client_order_number",
        field=models.CharField(
            blank=True,
            db_index=True,
            max_length=250,
            null=True,
            verbose_name="Номер заказа клиента",
        ),
    ),
    migrations.RemoveConstraint(
        model_name="salesorders",
        name="uniq_sales_order_combo",
    ),
]
