# Generated by Django 5.1.6 on 2026-02-14 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0014_remove_salesorders_uniq_sales_order_combo_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="salesorders",
            name="salesdata",
        ),
        migrations.AddField(
            model_name="salesdata",
            name="orders",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sales.salesorders",
                verbose_name="id заказа",
            ),
        ),
        migrations.AddConstraint(
            model_name="salesorders",
            constraint=models.UniqueConstraint(
                fields=("client_order", "client_order_date", "client_order_number"),
                name="uniq_sales_order_combo",
            ),
        ),
    ]
