# Generated by Django 5.1.6 on 2026-02-15 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_remove_salesorders_salesdata_salesdata_orders_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mvsalesorder',
            options={'managed': False, 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы (в реализации)'},
        ),
        migrations.AddField(
            model_name='salesdata',
            name='client_order_feature',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='Характеристика'),
        ),
        migrations.AlterField(
            model_name='salesdata',
            name='client_order_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер заказа'),
        ),
    ]
