# Generated by Django 5.1.6 on 2026-04-14 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_remove_orderitem_fullname_and_more"),
        ("sales", "0017_salesdata_order_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesdata",
            name="order_guid",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="Заказ GUID"
            ),
        ),
        migrations.AlterField(
            model_name="salesdata",
            name="order_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="orders.order",
                verbose_name="всегда null",
            ),
        ),
    ]
