# Generated by Django 5.1.6 on 2026-05-21 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate', '0025_barcode_spec'),
        ('sales', '0018_salesdata_order_guid_alter_salesdata_order_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSalesPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_month', models.DateField(verbose_name='Последний день планового месяца')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='План продаж')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corporate.stores', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'План продаж магазина',
                'verbose_name_plural': 'Планы продаж магазинов',
                'constraints': [models.UniqueConstraint(fields=('plan_month', 'store'), name='uniq_store_sales_plan_month')],
            },
        ),
    ]
